import type { Metadata } from "next";
import "./globals.css";
import { Box, Flex } from "@chakra-ui/react";
import { Provider } from "@/components/chakra-ui/provider";
import QueryProviders from "@/components/tanstack-query/provider";
import { Nav } from "@/app/_shared/nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body>
        <QueryProviders>
          <Provider>
            <Flex justifyContent="center" alignItems="start" h="100vh">
              <Box
                bg="white"
                borderRadius="md"
                boxShadow="sm"
                width={600}
                p={4}
                m={4}
              >
                <Nav />
                <br />
                {children}
              </Box>
            </Flex>
          </Provider>
        </QueryProviders>
      </body>
    </html>
  );
}
